version: '3.8'

services:
  frontend:
    build:
      context: ./fe
    environment:
      NODE_ENV: production
    ports:
      - 5174:5173

  backend:
    build:
      context: ./be
    ports:
      - 8082:9090

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg_hba.conf:/etc/postgresql/$PG_MAJOR/main/pg_hba.conf
      - ./be/CinemaSQLSchema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
