ALTER TABLE "movie_screening" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id");
ALTER TABLE "movie_screening" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("id");
ALTER TABLE "movie_screening" ADD FOREIGN KEY ("ticket_cost_id") REFERENCES "ticket_cost" ("id");
ALTER TABLE "movie" ADD FOREIGN KEY ("movie_genre_id") REFERENCES "movie_genre" ("id");
ALTER TABLE "movie_genre" ADD FOREIGN KEY ("movie_id") REFERENCES "movie" ("id");
ALTER TABLE "movie_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");
ALTER TABLE "seat" ADD FOREIGN KEY ("screen_id") REFERENCES "screen" ("id");
ALTER TABLE "schedule" ADD FOREIGN KEY ("movie_screening_id") REFERENCES "movie_screening" ("id");
ALTER TABLE "booking" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");